version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    depends_on:
      - db
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  db_data: