    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
              https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          fi

          echo "${{ secrets.GH_PAT }}" | sudo docker login ghcr.io -u altinshabani1 --password-stdin

          IMAGE_TAG="ghcr.io/altinshabani1/mini-saas:${{ github.sha }}"
          sudo docker pull $IMAGE_TAG
          sudo docker stop mini-saas || true
          sudo docker rm mini-saas || true
          sudo docker run -d --name mini-saas -p 80:3000 $IMAGE_TAG
